apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: default-ipv4-ippool
spec:
    blockSize: 26
    cidr: 172.27.0.0/16
    ipipMode: Never
    natOutgoing: false
    nodeSelector: all()
    vxlanMode: Never