# 
# 
# K8 Master Node #1.
# 
# 
---
# Node k8c1m0
apiVersion: projectcalico.org/v3
kind: Node
metadata:
  name: k8c1m0.labs.haystacknetworks.com
spec:
  bgp:
    # K8 Node IP/AS
    ipv4Address: 192.168.9.193/28
    asNumber: 63551

---
# ACI Leaf 1
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
      name: leaf201-k8c1m0
spec:
      # ACI Leaf IP/AS
      peerIP: 192.168.9.204
      asNumber: 63500
      # Apply to K8 Node
      node: k8c1m0.labs.haystacknetworks.com

---
# ACI Leaf 2
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
      name: leaf202-k8c1m0
spec:
      # ACI Leaf IP/AS
      peerIP: 192.168.9.205
      asNumber: 63500
      # Apply to K8 Node
      node: k8c1m0.labs.haystacknetworks.com
